export const availableScopes = [
  { value: 'identify', label: 'identify', description: "Access user's identity" },
  { value: 'email', label: 'email', description: "Access user's email" },
  { value: 'connections', label: 'connections', description: "Access user's connections" },
  { value: 'guilds', label: 'guilds', description: "Access user's guilds" },
  { value: 'guilds.join', label: 'guilds.join', description: 'Join guilds for user' },
  { value: 'guilds.members.read', label: 'guilds.members.read', description: 'Read guild members' },
  { value: 'guilds.channels.read', label: 'guilds.channels.read', description: 'Read guild channels' },
  { value: 'gdm.join', label: 'gdm.join', description: 'Join group DMs' },
  { value: 'bot', label: 'bot', description: 'Add bot to server' },
  { value: 'rpc', label: 'rpc', description: 'RPC access' },
  { value: 'rpc.notifications.read', label: 'rpc.notifications.read', description: 'Read RPC notifications' },
  { value: 'rpc.voice.read', label: 'rpc.voice.read', description: 'Read RPC voice' },
  { value: 'rpc.voice.write', label: 'rpc.voice.write', description: 'Write RPC voice' },
  { value: 'rpc.video.read', label: 'rpc.video.read', description: 'Read RPC video' },
  { value: 'rpc.video.write', label: 'rpc.video.write', description: 'Write RPC video' },
  { value: 'rpc.screenshare.read', label: 'rpc.screenshare.read', description: 'Read RPC screenshare' },
  { value: 'rpc.screenshare.write', label: 'rpc.screenshare.write', description: 'Write RPC screenshare' },
  { value: 'rpc.activities.write', label: 'rpc.activities.write', description: 'Write RPC activities' },
  { value: 'webhook.incoming', label: 'webhook.incoming', description: 'Incoming webhooks' },
  { value: 'messages.read', label: 'messages.read', description: 'Read messages' },
  { value: 'applications.builds.upload', label: 'applications.builds.upload', description: 'Upload application builds' },
  { value: 'applications.builds.read', label: 'applications.builds.read', description: 'Read application builds' },
  { value: 'applications.commands', label: 'applications.commands', description: 'Use slash commands' },
  { value: 'applications.commands.permissions.update', label: 'applications.commands.permissions.update', description: 'Update command permissions' },
  { value: 'applications.store.update', label: 'applications.store.update', description: 'Update application store' },
  { value: 'applications.entitlements', label: 'applications.entitlements', description: 'Application entitlements' },
  { value: 'activities.read', label: 'activities.read', description: 'Read activities' },
  { value: 'activities.write', label: 'activities.write', description: 'Write activities' },
  { value: 'activities.invites.write', label: 'activities.invites.write', description: 'Write activity invites' },
  { value: 'relationships.read', label: 'relationships.read', description: 'Read relationships' },
  { value: 'relationships.write', label: 'relationships.write', description: 'Write relationships' },
  { value: 'voice', label: 'voice', description: 'Voice access' },
  { value: 'dm_channels.read', label: 'dm_channels.read', description: 'Read DM channels' },
  { value: 'dm_channels.messages.read', label: 'dm_channels.messages.read', description: 'Read DM messages' },
  { value: 'dm_channels.messages.write', label: 'dm_channels.messages.write', description: 'Write DM messages' },
  { value: 'role_connections.write', label: 'role_connections.write', description: 'Write role connections' },
  { value: 'presences.read', label: 'presences.read', description: 'Read presences' },
  { value: 'presences.write', label: 'presences.write', description: 'Write presences' },
  { value: 'openid', label: 'openid', description: 'OpenID Connect' },
  { value: 'account.global_name.update', label: 'account.global_name.update', description: 'Update global name' },
  { value: 'payment_sources.country_code', label: 'payment_sources.country_code', description: 'Payment country code' },
  { value: 'sdk.social_layer', label: 'sdk.social_layer', description: 'SDK social layer' },
  { value: 'sdk.social_layer_presence', label: 'sdk.social_layer_presence', description: 'SDK social layer presence' },
  { value: 'gateway.connect', label: 'gateway.connect', description: 'Connect to gateway' },
  { value: 'lobbies.write', label: 'lobbies.write', description: 'Write lobbies' },
  { value: 'application_identities.write', label: 'application_identities.write', description: 'Write application identities' },
];